name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goos: darwin
            goarch: arm64

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.21'

    - name: Build Go app
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: |
        CGO_ENABLED=0 go build -o ./ApproveGuard-${{ matrix.goos }}-${{ matrix.goarch }} --ldflags '-w -s -extldflags "-static"  -X main.version=${{ github.ref_name }}' .

    - name: List files
      run: ls -lh

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ApproveGuard-${{ matrix.goos }}-${{ matrix.goarch }}
        path: ./ApproveGuard-${{ matrix.goos }}-${{ matrix.goarch }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download all artifacts
      uses: actions/download-artifact@v3

    - name: List all downloaded artifacts
      run: ls -la

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ./ApproveGuard-*/*
      env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}

    # - name: Build and push Docker image
    #   uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
    #   with:
    #     context: .
    #     file: ./Dockerfile
    #     platforms: ${{ matrix.platforms }}
    #     push: true
    #     outputs: type=image,name=target,annotation-index.org.opencontainers.image.description=ApproveGuard multi-arch image
    #   env:
    #       GITHUB_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
